name: fianl
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.6
  time_planner: ^0.1.1
  flutter_tts: ^3.1.1 
  path_provider: ^2.0.2
  english_words: ^4.0.0
  provider: ^6.0.5
  speech_to_text: ^6.1.1
  animations: ^2.0.7
  tuple: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - ./images/user.png
    - ./images/pic1.jpg
    - ./images/pic2.jpg
    - ./images/pic3.jpg
    - ./images/pic4.jpg
    - ./images/pic5.jpg
    - ./images/pic6.jpg
    - ./images/pic7.jpg
    - ./images/pic8.jpg
    - ./images/pic9.jpg
    - ./images/pic10.jpg
    - ./images/pic11.jpg
    - ./images/pic12.jpg
    - ./images/1.1.png
    - ./images/1.2.png
    - ./images/2.1.png
    - ./images/2.2.png
    - ./images/3.3.png
    - ./images/4.1.png
    - ./images/p1.png
    - ./images/p2.jpg
    - ./images/p3.jpg
    - ./images/p4.jpg
    - ./images/p5.jpg
    - ./images/p6.jpg
    - ./images/p7.jpg
    - ./images/p8.jpg
    - ./images/p9.jpg
    - ./images/logo2.png
    - ./images/kidinfo.png
    - ./images/p10.jpg
    - ./images/p11.jpg
    - ./images/p12.jpg
    - ./images/p13.jpg
    - ./images/p14.jpg
    - ./images/p15.jpg
    - ./images/p16.jpg
    - ./images/p17.jpg
    - ./images/p18.jpg
    - ./images/p19.jpg
    - ./images/p20.jpg
    - ./images/p21.jpg
    - ./images/p22.jpg
    - ./images/p23.jpg
    - ./images/p24.jpg
    - ./images/p25.jpg
    - ./images/p26.jpg
    - ./images/p27.jpg
    - ./images/p28.jpg
    - ./images/p29.jpg
    - ./images/p30.jpg
    - ./images/p31.jpg
    - ./images/p32.jpg
    - ./images/p33.jpg
    - ./images/p34.jpg
    - ./images/p35.jpg
    - ./images/p36.jpg
    - ./images/p37.jpg
    - ./images/p38.jpg
    - ./images/p39.jpg
    - ./images/p40.jpg
    - ./images/p41.jpg
    - ./images/p42.jpg
    - ./images/f1.jpg
    - ./images/f2.jpg
    - ./images/f3.jpg
    - ./images/f4.jpg
    - ./images/f5.jpg
    - ./images/f6.jpg
